### ISSUE TITLE
收集海外放送／P2P下载的具体地址

### ISSUE THREAD

**Issue by bitinn** [wxt2005/new_bangumi#4]
个人想补足各种正版放送和P2P下载的选项，基于现在的审查问题：

http://bitinn.net/11249/

https://twitter.com/bitinn/status/588904413416173568

链接最好是特定一部作品的放送专页，可以选任何一集看的页面。

退而求次之的是标签页或搜索结果。

欢迎回报，除了国内已知的几家，目前的选项包括：

nico、daisuki、crunchyroll、funimation、hulu（估计都没中文字幕）

P2P下载还是极影、漫游、动漫花园？

**Comment by bitinn** [comment]
当前的设计，要修改的代码不多，估计这两处就行。

https://github.com/wxt2005/new_bangumi/blob/jquery/js/main.js#L25
https://github.com/wxt2005/new_bangumi/blob/jquery/js/main.js#L284

然后更新json文件即可。

唯一的问题是太多链接可能不好看，UI上我不知是否需要调整，select/option下拉菜单可以但是可能使用上不如链接方便。

**Comment by bitinn** [comment]
P2P链接比较好搞，几家都是搜索为基础的，用作品名的关键字即可

漫游的格式
http://share.popgo.org/search.php?title=XXXX

动漫花园的格式
http://share.dmhy.org/topics/list?keyword=XXXX

Nyaa
http://www.nyaa.se/?page=search&term=XXXX

**Comment by bitinn** [comment]
nico有个动画专题（TV放映中タイトル栏目），估计要翻墙
http://ch.nicovideo.jp/portal/anime

daisuki不多，这期好像就4-5部新番有上，似乎限区，反正我没能打开
http://www.daisuki.net/anime/

crunchyroll很全，但是限区，删除cookie走北美IP能看到完整列表，可以看
http://www.crunchyroll.com/videos/anime/simulcasts

funimation也不多，有些可能是独播，收费only
http://www.funimation.com/videos/simulcasts_shows

hulu限区，而且能检测来自代理，翻墙也不行
http://www.hulu.com/browse/picks/simulcasts

简单而言，下载可能还更靠谱……

**Comment by wxt2005** [comment]
v2 版本添加了花园、漫游、Nyaa 的搜索链接，可以访问 http://bgmlist.com 使用。
[repo 地址](https://github.com/wxt2005/bangumi-list)

由于是自动用中文或日文名进行搜索，可能会出现不准确的情况。
