### ISSUE TITLE
[Feature Request] 添加 Bangumi.tv 的链接

### ISSUE THREAD

**Issue by yume-chan** [wxt2005/new_bangumi#6]
Bangumi.tv 提供了中文的番组信息，并且有用户评分和注册后记录观看进度的功能。

另外如果能添加的话，我希望能用在我的非官方 Bangumi.tv 手机客户端中，因为 Bangumi.tv 本身的放送列表更新并不及时，Bangumi.tv 也不提供国内版权方信息。

**Comment by wxt2005** [comment]
下一版将加入Bangumi链接。

想请教一下，用在手机客户端中是什么意思，大概是什么样一种形式？

**Comment by yume-chan** [comment]
![Calendar View](https://cloud.githubusercontent.com/assets/1330321/7361799/b0f46fee-ed91-11e4-88f3-545c98419313.png)
这是目前的放送列表界面，数据源是 Bangumi.tv 的每日放送，点击则会进入对应项目的详细信息页面。因此需要添加的数据有 Bangumi.tv 的链接和项目的封面，中文名和原文名则至少需要一项。下方的观看人数可以改为其它项目。
高亮的项目并不是已放送的项目，而是用户正在看的项目。

![Detail View](https://cloud.githubusercontent.com/assets/1330321/7361800/bdb60c7e-ed91-11e4-93b4-0944d6e9dfc2.png)
这是项目的详细信息页面，如果 bgmlist 提供了此番组的信息（例如版权方信息，详细放送时间）的话（通过 Bangumi.tv 项目 ID 进行匹配），可以显示在简介的下方。

另外在信息附近的明显位置将以链接形式提供 bgmlist 的地址。

**Comment by yume-chan** [comment]
Any update?

**Comment by wxt2005** [comment]
你好，v2 版本已添加 bangumi 地址，可以访问 http://bgmlist.com 使用。
[repo 地址](https://github.com/wxt2005/bangumi-list)
谢谢！
